apiVersion: v1
kind: Service
metadata:
  labels:
    app: curso-mc
  name: curso-mc
  namespace: java
spec:
  type: NodePort
  selector:
    app: curso-mc
  ports:
  - name: "curso-mc-service"
    port: 5000
    targetPort: 8080
    nodePort: 31000
